import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export const skills = [
  'Python',
  'JavaScript',
  'Java',
  'C',
  'C++',
  'C#',
  'Swift',
  'Kotlin',
  'Ruby',
  'Go',
  'Rust',
  'PHP',
  'TypeScript',
  'SQL',
  'NoSQL',
  'HTML',
  'CSS',
  'Sass',
  'R',
  'Scala',
  'Perl',
  'Lua',
  'Dart',
  'Objective-C',
  'Haskell',
  'Elixir',
  'Erlang',
  'GraphQL',
  'REST APIs',
  'gRPC',
  'Docker',
  'Kubernetes',
  'Terraform',
  'AWS',
  'Azure',
  'Google Cloud',
  'Firebase',
  'MongoDB',
  'PostgreSQL',
  'MySQL',
  'SQLite',
  'Redis',
  'Cassandra',
  'Neo4j',
  'Elasticsearch',
  'Flask',
  'Django',
  'FastAPI',
  'Spring Boot',
  'Node.js',
  'Express.js',
  'NestJS',
  'ASP.NET',
  'Ruby on Rails',
  'Laravel',
  'Vue.js',
  'React',
  'Angular',
  'Svelte',
  'Next.js',
  'Nuxt.js',
  'Tailwind CSS',
  'Bootstrap',
  'Material-UI',
  'Flutter',
  'React Native',
  'SwiftUI',
  'Jetpack Compose',
  'Unity',
  'Unreal Engine',
  'TensorFlow',
  'PyTorch',
  'OpenCV',
  'Scikit-learn',
  'Pandas',
  'NumPy',
  'Matplotlib',
  'Seaborn',
  'Keras',
  'Hadoop',
  'Spark',
  'Kafka',
  'Airflow',
  'Tableau',
  'Power BI',
  'Jenkins',
  'Git',
  'GitHub Actions',
  'CircleCI',
  'Ansible',
  'Prometheus',
  'Grafana',
  'Blockchain',
  'Solidity',
  'WebAssembly',
  'Linux',
  'Bash',
  'PowerShell',
  'Raspberry Pi',
  'Embedded C',
  'Data Science',
  'Data Engineering',
  'ETL',
  'Snowflake',
  'BigQuery',
  'Redshift',
  'Spark SQL',
  'DynamoDB',
  'RabbitMQ',
  'CI/CD',
  'DevOps',
  'Agile',
  'Scrum',
  'JIRA',
  'Postman',
  'Insomnia',
  'JWT',
  'OAuth2',
  'Cybersecurity',
  'Penetration Testing',
  'OWASP',
  'Reverse Engineering',
  'Game Development',
  'Microservices',
  'Serverless',
  'Event-Driven Architecture',
  'Domain-Driven Design',
  'Web Components',
  'Webpack',
  'Vite',
  'ESBuild',
  'Unit Testing',
  'Integration Testing',
  'E2E Testing',
  'TDD',
  'BDD',
  'Jest',
  'Mocha',
  'Cypress',
  'Selenium',
  'Playwright',
  'Observability',
  'Datadog',
  'Sentry',
  'MLflow',
  'MLOps',
  'IoT',
  'Quantum Computing',
  'Qiskit',
  'Augmented Reality',
  'Virtual Reality',
  'Ethereum',
  'Smart Contracts',
  'Web3.js',
  'Cryptography',
  'SHA-256',
  'Bcrypt',
  'Parallel Computing',
  'CUDA',
  'OpenCL',
  'Software Architecture',
  'Design Patterns',
  'SOLID Principles',
  'Clean Code',
  'Refactoring',
  'Code Reviews',
  'Version Control',
  'Git Workflows',
];

async function main() {
  for (const skill of skills) {
    await prisma.skill.upsert({
      where: { name: skill },
      update: {},
      create: { name: skill },
    });
  }

  console.log('✅ Default skills inserted!');
}

main()
  .catch((e) => console.error(e))
  .finally(() => prisma.$disconnect());
